# Autenticação
MIN_PASSWORD_LENGTH = 8
MAX_LOGIN_ATTEMPTS = 5
ACCESS_TOKEN_MINUTES = 15
REFRESH_TOKEN_DAYS = 7
STEP_TOKEN_MINUTES = 5
MAX_SESSIONS_PER_USER = 5
REGISTRATION_TOKEN_DAYS = 7
ADMIN_ACTION_TOKEN_MINUTES = 5

# MFA
MFA_ISSUER = "InvUBI"
MFA_VALID_WINDOW = 1
MFA_STEP_COOKIE_NAME = "mfa_step"
MFA_STEP_COOKIE_PATH = "/api/auth"

# Cookies
REFRESH_TOKEN_COOKIE_NAME = "refresh_token"
REFRESH_TOKEN_PATH = "/api/auth"

# Argon2id
ARGON2_TIME_COST = 3
ARGON2_MEMORY_COST = 65536
ARGON2_PARALLELISM = 4

# AuditLog origins
ORIGIN_USER = "utilizador"
ORIGIN_SCHEDULER_MANUTENCAO = "scheduler_manutencao"
