# Autenticação
MIN_PASSWORD_LENGTH = 8
LOGIN_RATE_LIMIT = "5 per minute"
ACCESS_TOKEN_MINUTES = 15
REFRESH_TOKEN_HOURS = 1
STEP_TOKEN_MINUTES = 5
MAX_SESSIONS_PER_USER = 5
REGISTRATION_TOKEN_DAYS = 7
PASSWORD_RESET_TOKEN_MINUTES = 30
PASSWORD_RESET_REQUEST_RATE_LIMIT = "5 per hour"
PASSWORD_RESET_VALIDATE_RATE_LIMIT = "20 per minute"
PASSWORD_RESET_COMPLETE_RATE_LIMIT = "5 per hour"
PASSWORD_RESET_RESPONSE_MIN_SECONDS = 0.3
PASSWORD_RESET_RESPONSE_JITTER_MILLISECONDS = 200
PASSWORD_CHANGE_RATE_LIMIT = "5 per minute"
PASSWORD_CHANGE_STEP_COOKIE_NAME = "password_change_step"
PASSWORD_CHANGE_STEP_COOKIE_PATH = "/api/auth/password-change"

# MFA
MFA_ISSUER = "InvUBI"
MFA_VALID_WINDOW = 1
MFA_STEP_COOKIE_NAME = "mfa_step"
MFA_STEP_COOKIE_PATH = "/api/auth"
MFA_RECOVERY_CODE_LENGTH = 16
MFA_RECOVERY_RATE_LIMIT = "5 per minute"

# Cookies
REFRESH_TOKEN_COOKIE_NAME = "refresh_token"
REFRESH_TOKEN_PATH = "/api/auth"
REFRESH_CSRF_COOKIE_NAME = "csrf_refresh_token"
CSRF_HEADER_NAME = "X-CSRF-TOKEN"

# Argon2id
ARGON2_TIME_COST = 3
ARGON2_MEMORY_COST = 65536
ARGON2_PARALLELISM = 4

# AuditLog origins
ORIGIN_USER = "utilizador"
ORIGIN_SCHEDULER_MANUTENCAO = "scheduler_manutencao"
